package coreclient

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// loadP58Fixture reads one of the recorded Core response fixtures from
// testdata/p58. Those fixtures were generated by Core's
// TestP58SellerContractShapes handler test and are pinned to the Core commit
// recorded in testdata/p58/CORE_SHA.txt. They are the source of truth for the
// decode shapes in catalog_orders.go; if Core's contract changes, regenerate
// the fixtures and update the DTOs together.
func loadP58Fixture(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "p58", name))
	if err != nil {
		t.Fatalf("read fixture %s: %v", name, err)
	}
	return data
}

func decodeP58Fixture(t *testing.T, name string, dst any) {
	t.Helper()
	if err := json.Unmarshal(loadP58Fixture(t, name), dst); err != nil {
		t.Fatalf("decode fixture %s into %T: %v", name, dst, err)
	}
}

func TestContractProductList(t *testing.T) {
	var res SellerProductListResponse
	decodeP58Fixture(t, "product-list.json", &res)

	if res.Total != 1 || res.Limit != 25 || res.Offset != 0 {
		t.Fatalf("unexpected page envelope: total=%d limit=%d offset=%d", res.Total, res.Limit, res.Offset)
	}
	if len(res.Products) != 1 {
		t.Fatalf("expected 1 product, got %d", len(res.Products))
	}
	item := res.Products[0]
	if item.Product.ID == "" || item.Product.Slug != "contract-product" {
		t.Fatalf("unexpected embedded product: %+v", item.Product)
	}
	if item.Source != "seller_owned" || item.Name != "Contract Product" {
		t.Fatalf("unexpected source/name: %q/%q", item.Source, item.Name)
	}
	if item.ListingID == "" || item.ListingStatus != "inactive" {
		t.Fatalf("unexpected listing fields: id=%q status=%q", item.ListingID, item.ListingStatus)
	}
	if item.CurrentPrice == nil || item.CurrentPrice.Amount != 15000 || item.CurrentPrice.Currency != "EGP" {
		t.Fatalf("unexpected current_price: %+v", item.CurrentPrice)
	}
	if item.InventorySummary.TotalOnHand != 30 || item.InventorySummary.TotalAvailable != 30 {
		t.Fatalf("unexpected inventory totals: %+v", item.InventorySummary)
	}
	if len(item.InventorySummary.Locations) != 1 || item.InventorySummary.Locations[0].LocationName != "Main Warehouse" {
		t.Fatalf("unexpected inventory locations: %+v", item.InventorySummary.Locations)
	}
	if !item.PublishReadiness.IsReady {
		t.Fatalf("expected publish readiness")
	}
}

func TestContractProductDetail(t *testing.T) {
	var detail SellerProductDetail
	decodeP58Fixture(t, "product-detail.json", &detail)

	if detail.Product.ID == "" || detail.Product.Status != "active" {
		t.Fatalf("unexpected product: %+v", detail.Product)
	}
	if detail.Source != "seller_owned" {
		t.Fatalf("unexpected source: %q", detail.Source)
	}
	// category_ids is the contract field name; a "categories" shape must not be
	// assumed even though the fixture array is empty.
	if detail.CategoryIDs == nil {
		t.Fatal("category_ids missing from decoded detail")
	}
	if len(detail.Translations) != 2 || len(detail.Variants) != 1 || len(detail.SKUs) != 1 || len(detail.Media) != 1 {
		t.Fatalf("unexpected collections: translations=%d variants=%d skus=%d media=%d",
			len(detail.Translations), len(detail.Variants), len(detail.SKUs), len(detail.Media))
	}
	if detail.Listing.ID == "" || detail.Listing.Status != "active" {
		t.Fatalf("unexpected listing: %+v", detail.Listing)
	}
	if detail.CurrentPrice == nil || detail.CurrentPrice.Amount != 15000 || detail.CurrentPrice.Currency != "EGP" {
		t.Fatalf("unexpected current_price: %+v", detail.CurrentPrice)
	}
	if detail.InventorySummary.TotalOnHand != 30 || len(detail.InventorySummary.Locations) != 1 {
		t.Fatalf("unexpected inventory_summary: %+v", detail.InventorySummary)
	}
	if detail.Presentation.SellerListingID == "" || len(detail.Presentation.Sections) != 2 {
		t.Fatalf("unexpected presentation: %+v", detail.Presentation)
	}
	if detail.PurchaseBehavior != "add_to_cart" {
		t.Fatalf("unexpected purchase_behavior: %q", detail.PurchaseBehavior)
	}
	if !detail.PublishReadiness.IsReady {
		t.Fatal("expected publish readiness")
	}
}

func TestContractLocationsEnvelope(t *testing.T) {
	var res StoreLocationListResponse
	decodeP58Fixture(t, "locations.json", &res)

	if len(res.Locations) != 1 {
		t.Fatalf("expected 1 location, got %d", len(res.Locations))
	}
	loc := res.Locations[0]
	if loc.ID == "" || loc.StoreID == "" {
		t.Fatalf("unexpected location identity: %+v", loc)
	}
	if loc.LocationType != "warehouse" || loc.MarketCode != "EG" || loc.Status != "active" {
		t.Fatalf("unexpected location fields: %+v", loc)
	}
	if loc.UpdatedAt.IsZero() {
		t.Fatal("updated_at missing from decoded location")
	}
}

func TestContractSingleLocation(t *testing.T) {
	var loc StoreLocation
	decodeP58Fixture(t, "location.json", &loc)

	if loc.LocationType != "warehouse" || loc.Name != "Main Warehouse" || loc.Code != "main" {
		t.Fatalf("unexpected location: %+v", loc)
	}
}

func TestContractInventoryEnvelope(t *testing.T) {
	var res SellerInventoryListResponse
	decodeP58Fixture(t, "inventory.json", &res)

	if len(res.Inventory) != 1 {
		t.Fatalf("expected 1 inventory row, got %d", len(res.Inventory))
	}
	row := res.Inventory[0]
	if row.ID == "" {
		t.Fatal("inventory row id missing")
	}
	if row.LocationName != "Main Warehouse" {
		t.Fatalf("unexpected location_name: %q", row.LocationName)
	}
	if row.AvailableQty != 30 || row.OnHandQty != 30 || row.ReservedQty != 0 {
		t.Fatalf("unexpected quantities: %+v", row)
	}
	if row.Version != 0 {
		t.Fatalf("unexpected version: %d", row.Version)
	}
}

func TestContractOrderDetail(t *testing.T) {
	var detail SellerOrderDetail
	decodeP58Fixture(t, "order-detail.json", &detail)

	if detail.ID == "" || detail.OrderNumber != "#100001" || detail.Status != "pending" {
		t.Fatalf("unexpected order identity: %+v", detail)
	}
	// Currency is an order-level field; items carry minor-unit integers only.
	if detail.Currency != "EGP" || detail.Subtotal != 30000 || detail.Total != 30000 || detail.ItemCount != 1 {
		t.Fatalf("unexpected order totals: %+v", detail)
	}
	if detail.ConfirmationDeadlineAt == nil || detail.ConfirmationDeadlineAt.IsZero() {
		t.Fatal("confirmation_deadline_at missing")
	}
	if detail.ContactEmail != "buyer@contract.test" {
		t.Fatalf("unexpected contact_email: %q", detail.ContactEmail)
	}
	if len(detail.Items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(detail.Items))
	}
	item := detail.Items[0]
	if item.UnitPrice != 15000 || item.TotalPrice != 30000 || item.Quantity != 2 {
		t.Fatalf("unexpected item amounts: %+v", item)
	}
	if item.Source != "seller_owned" || item.SKUCode != "SKU-CONTRACT-1" {
		t.Fatalf("unexpected item fields: %+v", item)
	}
	if len(detail.Timeline) != 1 || detail.Timeline[0].Type != "pending" || detail.Timeline[0].ID == "" {
		t.Fatalf("unexpected timeline: %+v", detail.Timeline)
	}
	if len(detail.AllowedNextActions) != 2 || detail.AllowedNextActions[0] != "confirmed" {
		t.Fatalf("unexpected allowed_next_actions: %v", detail.AllowedNextActions)
	}
	if detail.ShippingAddress == nil || detail.ShippingAddress["recipient_name"] != "Test Buyer" {
		t.Fatalf("unexpected shipping_address: %v", detail.ShippingAddress)
	}
}

func TestContractOrderTransition(t *testing.T) {
	var detail SellerOrderDetail
	decodeP58Fixture(t, "order-transition.json", &detail)

	if detail.Status != "confirmed" {
		t.Fatalf("unexpected status: %q", detail.Status)
	}
	if len(detail.Timeline) != 2 {
		t.Fatalf("expected 2 timeline entries, got %d", len(detail.Timeline))
	}
	if detail.ContactEmail == "" || len(detail.AllowedNextActions) != 2 {
		t.Fatalf("transition response must carry the same safe detail shape: email=%q actions=%v",
			detail.ContactEmail, detail.AllowedNextActions)
	}
}

func TestContractMediaPresign(t *testing.T) {
	var res MediaUploadResponse
	decodeP58Fixture(t, "media-presign.json", &res)

	if res.UploadURL == "" || res.StorageKey == "" || res.UploadToken == "" {
		t.Fatalf("unexpected presign payload: %+v", res)
	}
	if res.ExpiresAt.IsZero() {
		t.Fatal("expires_at missing from decoded presign payload")
	}
}

func TestContractMediaComplete(t *testing.T) {
	var meta MediaMetadata
	decodeP58Fixture(t, "media-complete.json", &meta)

	if meta.ID == "" || meta.MediaType != "image/webp" {
		t.Fatalf("unexpected media metadata: %+v", meta)
	}
	if meta.StorageKey == "" || !meta.IsPrimary {
		t.Fatalf("unexpected media fields: key=%q primary=%v", meta.StorageKey, meta.IsPrimary)
	}
	if meta.UpdatedAt.IsZero() {
		t.Fatal("updated_at missing from decoded media metadata")
	}
}

func TestContractPresentation(t *testing.T) {
	var pres SellerListingPresentation
	decodeP58Fixture(t, "presentation.json", &pres)

	if pres.SellerListingID == "" || pres.SchemaVersion != 1 || pres.PurchaseBehavior != "add_to_cart" {
		t.Fatalf("unexpected presentation header: %+v", pres)
	}
	if len(pres.Sections) != 2 {
		t.Fatalf("expected 2 sections, got %d", len(pres.Sections))
	}
	if pres.CreatedAt.IsZero() || pres.UpdatedAt.IsZero() {
		t.Fatal("created_at/updated_at missing from decoded presentation")
	}
}
